<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class FacturaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos=[
            [
                'CodigoF' => 1,
                'Numero' => 8,
                'cliente' => 13,
                'formaPago' => 1,
                'Entrada' => '2020-07-20',
                'Salida' => '2020-07-23',
                'Total' => 210000,
            ],
            [
                'CodigoF' => 2,
                'Numero' => 14,
                'cliente' => 6,
                'formaPago' => 3,
                'Entrada' => '2020-07-25',
                'Salida' => '2020-07-27',
                'Total' => 320000,
            ],
            [
                'CodigoF' => 3,
                'Numero' => 18,
                'cliente' => 15,
                'formaPago' => 2,
                'Entrada' => '2020-07-28',
                'Salida' => '2020-07-31',
                'Total' => 300000,
            ],
            [
                'CodigoF' => 4,
                'Numero' => 5,
                'cliente' => 1,
                'formaPago' => 2,
                'Entrada' => '2020-08-01',
                'Salida' => '2020-08-05',
                'Total' => 160000,
            ],
            [
                'CodigoF' => 5,
                'Numero' => 11,
                'cliente' => 9,
                'formaPago' => 1,
                'Entrada' => '2020-08-02',
                'Salida' => '2020-08-03',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 6,
                'Numero' => 8,
                'cliente' => 20,
                'formaPago' => 1,
                'Entrada' => '2020-08-04',
                'Salida' => '2020-08-08',
                'Total' => 280000,
            ],
            [
                'CodigoF' => 7,
                'Numero' => 2,
                'cliente' => 14,
                'formaPago' => 1,
                'Entrada' => '2020-08-08',
                'Salida' => '2020-08-09',
                'Total' => 40000,
            ],
            [
                'CodigoF' => 8,
                'Numero' => 16,
                'cliente' => 19,
                'formaPago' => 3,
                'Entrada' => '2020-08-10',
                'Salida' => '2020-08-14',
                'Total' => 360000,
            ],
            [
                'CodigoF' => 9,
                'Numero' => 4,
                'cliente' => 2,
                'formaPago' => 3,
                'Entrada' => '2020-08-15',
                'Salida' => '2020-08-18',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 10,
                'Numero' => 20,
                'cliente' => 8,
                'formaPago' => 1,
                'Entrada' => '2020-08-19',
                'Salida' => '2020-08-21',
                'Total' => 200000,
            ],
            [
                'CodigoF' => 11,
                'Numero' => 14,
                'cliente' => 4,
                'formaPago' => 1,
                'Entrada' => '2020-08-22',
                'Salida' => '2020-08-26',
                'Total' => 640000,
            ],
            [
                'CodigoF' => 12,
                'Numero' => 9,
                'cliente' => 20,
                'formaPago' => 1,
                'Entrada' => '2020-08-27',
                'Salida' => '2020-08-29',
                'Total' => 140000,
            ],
            [
                'CodigoF' => 13,
                'Numero' => 3,
                'cliente' => 15,
                'formaPago' => 1,
                'Entrada' => '2020-09-01',
                'Salida' => '2020-09-04',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 14,
                'Numero' => 15,
                'cliente' => 16,
                'formaPago' => 2,
                'Entrada' => '2020-12-16',
                'Salida' => NULL,
                'Total' => NULL,
            ],
            [
                'CodigoF' => 15,
                'Numero' => 6,
                'cliente' => 17,
                'formaPago' => 3,
                'Entrada' => '2020-09-07',
                'Salida' => '2020-09-12',
                'Total' => 350000,
            ],
            [
                'CodigoF' => 16,
                'Numero' => 19,
                'cliente' => 12,
                'formaPago' => 1,
                'Entrada' => '2020-09-10',
                'Salida' => '2020-09-12',
                'Total' => 200000,
            ],
            [
                'CodigoF' => 17,
                'Numero' => 3,
                'cliente' => 10,
                'formaPago' => 2,
                'Entrada' => '2020-09-13',
                'Salida' => '2020-09-15',
                'Total' => 80000,
            ],
            [
                'CodigoF' => 18,
                'Numero' => 10,
                'cliente' => 3,
                'formaPago' => 1,
                'Entrada' => '2020-09-17',
                'Salida' => '2020-09-19',
                'Total' => 240000,
            ],
            [
                'CodigoF' => 19,
                'Numero' => 1,
                'cliente' => 13,
                'formaPago' => 1,
                'Entrada' => '2020-09-20',
                'Salida' => '2020-09-21',
                'Total' => 40000,
            ],
            [
                'CodigoF' => 20,
                'Numero' => 18,
                'cliente' => 20,
                'formaPago' => 3,
                'Entrada' => '2020-09-23',
                'Salida' => '2020-09-24',
                'Total' => 100000,
            ],
            [
                'CodigoF' => 21,
                'Numero' => 5,
                'cliente' => 15,
                'formaPago' => 1,
                'Entrada' => '2020-09-25',
                'Salida' => '2020-09-29',
                'Total' => 160000,
            ],
            [
                'CodigoF' => 22,
                'Numero' => 10,
                'cliente' => 11,
                'formaPago' => 1,
                'Entrada' => '2020-09-28',
                'Salida' => '2020-09-30',
                'Total' => 240000,
            ],
            [
                'CodigoF' => 23,
                'Numero' => 20,
                'cliente' => 13,
                'formaPago' => 3,
                'Entrada' => '2020-09-30',
                'Salida' => '2020-10-03',
                'Total' => 300000,
            ],
            [
                'CodigoF' => 24,
                'Numero' => 14,
                'cliente' => 5,
                'formaPago' => 2,
                'Entrada' => '2020-10-01',
                'Salida' => '2020-10-03',
                'Total' => 320000,
            ],
            [
                'CodigoF' => 25,
                'Numero' => 18,
                'cliente' => 16,
                'formaPago' => 1,
                'Entrada' => '2020-10-03',
                'Salida' => '2020-10-06',
                'Total' => 300000,
            ],
            [
                'CodigoF' => 26,
                'Numero' => 12,
                'cliente' => 17,
                'formaPago' => 1,
                'Entrada' => '2020-10-06',
                'Salida' => '2020-10-10',
                'Total' => 480000,
            ],
            [
                'CodigoF' => 27,
                'Numero' => 9,
                'cliente' => 19,
                'formaPago' => 3,
                'Entrada' => '2020-10-08',
                'Salida' => '2020-10-11',
                'Total' => 140000,
            ],
            [
                'CodigoF' => 28,
                'Numero' => 11,
                'cliente' => 2,
                'formaPago' => 1,
                'Entrada' => '2020-10-10',
                'Salida' => '2020-10-13',
                'Total' => 480000,
            ],
            [
                'CodigoF' => 29,
                'Numero' => 7,
                'cliente' => 10,
                'formaPago' => 1,
                'Entrada' => '2020-10-11',
                'Salida' => '2020-10-13',
                'Total' => 140000,
            ],
            [
                'CodigoF' => 30,
                'Numero' => 13,
                'cliente' => 12,
                'formaPago' => 3,
                'Entrada' => '2020-10-14',
                'Salida' => '2020-10-15',
                'Total' => 160000,
            ],
            [
                'CodigoF' => 31,
                'Numero' => 16,
                'cliente' => 9,
                'formaPago' => 3,
                'Entrada' => '2020-10-17',
                'Salida' => '2020-10-20',
                'Total' => 270000,
            ],
            [
                'CodigoF' => 32,
                'Numero' => 6,
                'cliente' => 8,
                'formaPago' => 1,
                'Entrada' => '2020-12-18',
                'Salida' => NULL,
                'Total' => NULL,
            ],
            [
                'CodigoF' => 33,
                'Numero' => 19,
                'cliente' => 3,
                'formaPago' => 1,
                'Entrada' => '2020-10-20',
                'Salida' => '2020-10-22',
                'Total' => 200000,
            ],
            [
                'CodigoF' => 34,
                'Numero' => 1,
                'cliente' => 18,
                'formaPago' => 2,
                'Entrada' => '2020-10-25',
                'Salida' => '2020-10-28',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 35,
                'Numero' => 12,
                'cliente' => 1,
                'formaPago' => 1,
                'Entrada' => '2020-10-28',
                'Salida' => '2020-10-30',
                'Total' => 240000,
            ],
            [
                'CodigoF' => 36,
                'Numero' => 16,
                'cliente' => 7,
                'formaPago' => 1,
                'Entrada' => '2020-10-30',
                'Salida' => '2020-11-01',
                'Total' => 180000,
            ],
            [
                'CodigoF' => 37,
                'Numero' => 17,
                'cliente' => 6,
                'formaPago' => 2,
                'Entrada' => '2020-10-31',
                'Salida' => '2020-11-02',
                'Total' => 180000,
            ],
            [
                'CodigoF' => 38,
                'Numero' => 7,
                'cliente' => 12,
                'formaPago' => 1,
                'Entrada' => '2020-11-01',
                'Salida' => '2020-11-03',
                'Total' => 140000,
            ],
            [
                'CodigoF' => 39,
                'Numero' => 20,
                'cliente' => 4,
                'formaPago' => 1,
                'Entrada' => '2020-11-04',
                'Salida' => '2020-11-05',
                'Total' => 100000,
            ],
            [
                'CodigoF' => 40,
                'Numero' => 3,
                'cliente' => 14,
                'formaPago' => 3,
                'Entrada' => '2020-11-06',
                'Salida' => '2020-11-09',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 41,
                'Numero' => 15,
                'cliente' => 9,
                'formaPago' => 1,
                'Entrada' => '2020-11-09',
                'Salida' => '2020-11-11',
                'Total' => 180000,
            ],
            [
                'CodigoF' => 42,
                'Numero' => 10,
                'cliente' => 2,
                'formaPago' => 1,
                'Entrada' => '2020-11-10',
                'Salida' => '2020-11-13',
                'Total' => 640000,
            ],
            [
                'CodigoF' => 43,
                'Numero' => 17,
                'cliente' => 1,
                'formaPago' => 2,
                'Entrada' => '2020-11-15',
                'Salida' => '2020-11-16',
                'Total' => 90000,
            ],
            [
                'CodigoF' => 44,
                'Numero' => 5,
                'cliente' => 11,
                'formaPago' => 1,
                'Entrada' => '2020-11-15',
                'Salida' => '2020-11-17',
                'Total' => 80000,
            ],
            [
                'CodigoF' => 45,
                'Numero' => 10,
                'cliente' => 14,
                'formaPago' => 3,
                'Entrada' => '2020-11-18',
                'Salida' => '2020-11-19',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 46,
                'Numero' => 2,
                'cliente' => 20,
                'formaPago' => 2,
                'Entrada' => '2020-12-10',
                'Salida' => '2020-12-13',
                'Total' => 120000,
            ],
            [
                'CodigoF' => 47,
                'Numero' => 19,
                'cliente' => 7,
                'formaPago' => 2,
                'Entrada' => '2020-12-17',
                'Salida' => NULL,
                'Total' => NULL,
            ],
            [
                'CodigoF' => 48,
                'Numero' => 1,
                'cliente' => 12,
                'formaPago' => 1,
                'Entrada' => '2020-11-30',
                'Salida' => '2020-12-01',
                'Total' => 40000,
            ],
            [
                'CodigoF' => 49,
                'Numero' => 4,
                'cliente' => 6,
                'formaPago' => 1,
                'Entrada' => '2020-12-03',
                'Salida' => '2020-12-05',
                'Total' => 80000,
            ],
            [
                'CodigoF' => 50,
                'Numero' => 13,
                'cliente' => 18,
                'formaPago' => 3,
                'Entrada' => '2020-12-07',
                'Salida' => '2020-12-08',
                'Total' => 80000,
            ]                                                         
        ];
        DB::table('factura')->insert($datos);    
    }
}
